
const jsdoc2md = require('jsdoc-to-markdown')
const fs = require('fs');

let s = `# Allez

Allez puts things up in s3, simply.

`

const docs = jsdoc2md.renderSync({ files: 'index.js' })

s += docs;

s += `> This file is automatically generated. See \`g_docs.js\` to make additions.`

fs.writeFileSync('README.md', s);


